[package]
name = "rpc"
version = "0.1.0"
edition = "2021"
default-run = "musig-cli"

[dependencies]
bdk_bitcoind_rpc = { workspace = true }
bdk_wallet = { workspace = true }
drop-stream = "0.3.2"
futures-util = { version = "0.3.31", default-features = false, features = ["alloc"] }
musig2 = { workspace = true }
prost = "0.13.5"
protocol = { path = "../protocol" }
serde = { version = "1.0.219", features = ["derive"] }
serde_with = { version = "3.14.0", features = ["hex"] }
thiserror = "2.0.12"
tokio = { version = "1.46.1", features = ["macros", "rt-multi-thread", "time"] }
tokio-stream = "0.1.17"
tonic = "0.13.1"
tracing = "0.1.41"
unimock = { version = "0.6.7", optional = true }
# Dependencies used only by the binary target(s):
# TODO: Consider making a workspace of separate packages to avoid pulling these into the library:
clap = { version = "4.5.41", features = ["derive"] }
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }

[build-dependencies]
tonic-build = "0.13.1"

[dev-dependencies]
rpc = { path = ".", features = ["unimock"] }
anyhow = "1.0.98"
assert_cmd = "2.0.17"
const_format = "0.2.34"
predicates = "3.1.3"

[lints.clippy]
pedantic = "warn"
# Enable selected 'nursery' and 'restriction' lints...
allow_attributes = "warn"
allow_attributes_without_reason = "warn"
branches_sharing_code = "warn"
exhaustive_enums = "warn"
iter_on_empty_collections = "warn"
iter_on_single_items = "warn"
missing_const_for_fn = "warn"
renamed_function_params = "warn"
significant_drop_tightening = "warn"
str_to_string = "warn"
try_err = "warn"
unused_trait_names = "warn"
use_self = "warn"
# Panics shall generally only result from bugs in callee code, so this gives too many false positives:
missing_panics_doc = { level = "allow", priority = 1 }
# Probably shouldn't annotate every (public) pure fn with '#[must_use]', so too many false positives:
must_use_candidate = { level = "allow", priority = 1 }
