[package]
name = "protocol"
version = "0.1.0"
edition = "2024"

[dependencies]
bdk_electrum = { workspace = true }
anyhow = "1.0.97"
dotenv = "0.15.0"
bdk_wallet = { workspace = true }
rand = "0.9.0"
musig2 = { workspace = true }
